### ISSUE TITLE
What if countries are not connected ?

### ISSUE THREAD

**Issue by IanaKhitsko** [DryWolfi/MIPZ_1#6]
https://github.com/DryWolfi/MIPZ_1/blob/193a94e5cdd4ff784ae544452b3e129d4f739101/MIPZ_1/Services/DataService.cs#L38

This cycle will last forever?

**Comment by DryWolfi** [comment]
Ideed, it's a bug.
To fix it some adition condition was added to the cycle
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Services/DataService.cs#L51-L55
After some days passed we are checking county if it has only one type of coins
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Services/DataService.cs#L76-L90
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Models/City.cs#L27-L32
Due to our inpute limitatins its impossible to have a mono coin country after a thousend days unless it's disconected from the others.
